# UK Uni Enrollments RAW
Notebook for exploring raw UK university enrollment data.

In [1]:
from pathlib import Path

import pandas as pd

from IPython.display import display



# Locate UK enrollment data folder whether notebook runs from workspace root or docs/

candidate_dirs = [

    Path.cwd() / "UniEnrollmentsUK",

    Path.cwd().parent / "UniEnrollmentsUK",

    Path("UniEnrollmentsUK"),

    Path("../UniEnrollmentsUK"),

]



uk_dir = next((path.resolve() for path in candidate_dirs if path.exists()), None)

if uk_dir is None:

    raise FileNotFoundError("Could not find the 'UniEnrollmentsUK' folder.")



csv_files = sorted(uk_dir.glob("*.csv"), key=lambda p: p.name.lower())

if not csv_files:

    raise FileNotFoundError(f"No CSV files found in: {uk_dir}")





def read_csv_robust(file_path: Path) -> pd.DataFrame:

    try:

        return pd.read_csv(file_path, low_memory=False)

    except Exception:

        return pd.read_csv(

            file_path,

            engine="python",

            sep=None,

            on_bad_lines="skip",

        )





uk_raw_tables = {}

uk_raw_combined_parts = []



for file_path in csv_files:

    df = read_csv_robust(file_path)

    table_name = file_path.stem.replace("-", "_").replace(" ", "_")

    uk_raw_tables[table_name] = df



    df_with_source = df.copy()

    df_with_source["source_file"] = file_path.name

    uk_raw_combined_parts.append(df_with_source)



uk_uni_enrollments_raw_df = pd.concat(uk_raw_combined_parts, ignore_index=True)



print(f"Loaded {len(csv_files)} UK files from: {uk_dir}")

print("Files:")

for path in csv_files:

    print(f"- {path.name}")



print(f"\nCombined rows: {len(uk_uni_enrollments_raw_df)}, Columns: {len(uk_uni_enrollments_raw_df.columns)}")

display(uk_uni_enrollments_raw_df.head(20))

Loaded 4 UK files from: C:\Users\neddp\ECC3479-Project-JRGS\UniEnrollmentsUK
Files:
- 2015-2019.csv
- 2016-2018.csv
- 2019.csv
- 2020-2025.csv

Combined rows: 424059, Columns: 12

,Title,"HE student enrolments by subject area, sex, first year marker, level of study, mode of study and country of HE provider",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,source_file,﻿﻿Title:,Table 52 - HE student enrolments by subject of study and permanent address,"HE student enrolments by CAH level 1 subject, sex, entrant marker, level of study, mode of study and country of HE provider"
0,Location,UK,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
1,Academic years,2014/15 to 2018/19,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
2,Data source,HESA,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
3,Data source link,https://www.hesa.ac.uk/data-and-analysis/sb255...,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
4,Data file canonical link,https://www.hesa.ac.uk/data-and-analysis/sb255...,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
5,Licence,Creative Commons Attribution 4.0 International...,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
6,Code page,Unicode UTF-8,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
7,Disclaimer,Please note that this data includes rounded to...,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
8,2014/15 total,"2,265,980",NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
9,2015/16 total,"2,279,430",NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
10,2016/17 total,"2,317,880",NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
11,2017/18 total,"2,343,095",NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
12,2018/19 total,"2,383,970",NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
13,Last updated,Jan-20,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-2019.csv,NaN,NaN,NaN
16,Subject Area,First year marker,Level of study,Mode of study,Country of HE provider,Sex,Academic Year,Number,2015-2019.csv,NaN,NaN,NaN
17,(1) Medicine & dentistry,All,All,Full-time,England,Female,2014/15,24835,2015-2019.csv,NaN,NaN,NaN
18,(1) Medicine & dentistry,All,All,Full-time,England,Male,2014/15,19275,2015-2019.csv,NaN,NaN,NaN
19,(1) Medicine & dentistry,All,All,Full-time,England,Other,2014/15,0,2015-2019.csv,NaN,NaN,NaN

In [2]:
# Profile each UK file structure (columns + sample rows)

for file_path in csv_files:

    print("\n" + "=" * 80)

    print(f"File: {file_path.name}")

    file_df = uk_raw_tables[file_path.stem.replace('-', '_').replace(' ', '_')]

    print(f"Shape: {file_df.shape}")

    print("Columns:", list(file_df.columns))

    display(file_df.head(8))

================================================================================
File: 2015-2019.csv
Shape: (134397, 8)
Columns: ['Title', 'HE student enrolments by subject area, sex, first year marker, level of study, mode of study and country of HE provider', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

,Title,"HE student enrolments by subject area, sex, first year marker, level of study, mode of study and country of HE provider",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Location,UK,NaN,NaN,NaN,NaN,NaN,NaN
1,Academic years,2014/15 to 2018/19,NaN,NaN,NaN,NaN,NaN,NaN
2,Data source,HESA,NaN,NaN,NaN,NaN,NaN,NaN
3,Data source link,https://www.hesa.ac.uk/data-and-analysis/sb255...,NaN,NaN,NaN,NaN,NaN,NaN
4,Data file canonical link,https://www.hesa.ac.uk/data-and-analysis/sb255...,NaN,NaN,NaN,NaN,NaN,NaN
5,Licence,Creative Commons Attribution 4.0 International...,NaN,NaN,NaN,NaN,NaN,NaN
6,Code page,Unicode UTF-8,NaN,NaN,NaN,NaN,NaN,NaN
7,Disclaimer,Please note that this data includes rounded to...,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
File: 2016-2018.csv
Shape: (134857, 8)
Columns: ['Title', 'HE student enrolments by subject area, sex, first year marker, level of study, mode of study and country of HE provider', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

,Title,"HE student enrolments by subject area, sex, first year marker, level of study, mode of study and country of HE provider",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Location,UK,NaN,NaN,NaN,NaN,NaN,NaN
1,Academic years,2013/14 to 2017/18,NaN,NaN,NaN,NaN,NaN,NaN
2,Data source,HESA,NaN,NaN,NaN,NaN,NaN,NaN
3,Data source link,https://www.hesa.ac.uk/data-and-analysis/sb252...,NaN,NaN,NaN,NaN,NaN,NaN
4,Data file canonical link,https://www.hesa.ac.uk/data-and-analysis/sb252...,NaN,NaN,NaN,NaN,NaN,NaN
5,Licence,Creative Commons Attribution 4.0 International...,NaN,NaN,NaN,NaN,NaN,NaN
6,Code page,Unicode UTF-8,NaN,NaN,NaN,NaN,NaN,NaN
7,Disclaimer,Please note that this data includes rounded to...,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
File: 2019.csv
Shape: (8, 2)
Columns: ['\ufeff\ufeffTitle:', 'Table 52 - HE student enrolments by subject of study and permanent address']

,﻿﻿Title:,Table 52 - HE student enrolments by subject of study and permanent address
0,Subtitle:,Academic years 2019/20 to 2024/25
1,Reference ID:,DT051 Table 52
2,Data source:,HESA
3,Data source link:,https://www.hesa.ac.uk/data-and-analysis/stude...
4,Data file canonical link:,https://www.hesa.ac.uk/data-and-analysis/stude...
5,Licence:,Creative Commons Attribution 4.0 International...
6,Date:,2026
7,Search:,NaN

================================================================================
File: 2020-2025.csv
Shape: (154797, 8)
Columns: ['Title', 'HE student enrolments by CAH level 1 subject, sex, entrant marker, level of study, mode of study and country of HE provider', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

,Title,"HE student enrolments by CAH level 1 subject, sex, entrant marker, level of study, mode of study and country of HE provider",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Location,UK,NaN,NaN,NaN,NaN,NaN,NaN
1,Academic years,2020/21 to 2024/25,NaN,NaN,NaN,NaN,NaN,NaN
2,Data source,HESA,NaN,NaN,NaN,NaN,NaN,NaN
3,Data collection,"051,054,056",NaN,NaN,NaN,NaN,NaN,NaN
4,Data source link,https://www.hesa.ac.uk/data-and-analysis/sb273...,NaN,NaN,NaN,NaN,NaN,NaN
5,Data file canonical link,https://www.hesa.ac.uk/data-and-analysis/sb273...,NaN,NaN,NaN,NaN,NaN,NaN
6,Licence,Creative Commons Attribution 4.0 International...,NaN,NaN,NaN,NaN,NaN,NaN
7,Code page,Unicode UTF-8,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Locate where the real data table starts in each file

for file_path in csv_files:

    key = file_path.stem.replace('-', '_').replace(' ', '_')

    df = uk_raw_tables[key]

    print("\n" + "=" * 80)

    print(file_path.name)



    preview_text = df.apply(lambda row: " | ".join(map(str, row.values)), axis=1)

    matches = preview_text[preview_text.str.contains("Subject of study|subject of study|CAH|Total", case=False, regex=True)]

    print("Candidate rows:", matches.index[:10].tolist())

    if len(matches.index) > 0:

        first_idx = int(matches.index[0])

        start = max(0, first_idx - 3)

        end = min(len(df), first_idx + 8)

        display(df.iloc[start:end])

================================================================================
2015-2019.csv

Candidate rows: [7, 8, 9, 10, 11, 12, 20, 24, 28, 32]

,Title,"HE student enrolments by subject area, sex, first year marker, level of study, mode of study and country of HE provider",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
4,Data file canonical link,https://www.hesa.ac.uk/data-and-analysis/sb255...,NaN,NaN,NaN,NaN,NaN,NaN
5,Licence,Creative Commons Attribution 4.0 International...,NaN,NaN,NaN,NaN,NaN,NaN
6,Code page,Unicode UTF-8,NaN,NaN,NaN,NaN,NaN,NaN
7,Disclaimer,Please note that this data includes rounded to...,NaN,NaN,NaN,NaN,NaN,NaN
8,2014/15 total,"2,265,980",NaN,NaN,NaN,NaN,NaN,NaN
9,2015/16 total,"2,279,430",NaN,NaN,NaN,NaN,NaN,NaN
10,2016/17 total,"2,317,880",NaN,NaN,NaN,NaN,NaN,NaN
11,2017/18 total,"2,343,095",NaN,NaN,NaN,NaN,NaN,NaN
12,2018/19 total,"2,383,970",NaN,NaN,NaN,NaN,NaN,NaN
13,Last updated,Jan-20,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
2016-2018.csv

Candidate rows: [7, 8, 9, 10, 11, 12, 20, 24, 28, 32]

,Title,"HE student enrolments by subject area, sex, first year marker, level of study, mode of study and country of HE provider",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
4,Data file canonical link,https://www.hesa.ac.uk/data-and-analysis/sb252...,NaN,NaN,NaN,NaN,NaN,NaN
5,Licence,Creative Commons Attribution 4.0 International...,NaN,NaN,NaN,NaN,NaN,NaN
6,Code page,Unicode UTF-8,NaN,NaN,NaN,NaN,NaN,NaN
7,Disclaimer,Please note that this data includes rounded to...,NaN,NaN,NaN,NaN,NaN,NaN
8,2013/14 total,2299460,NaN,NaN,NaN,NaN,NaN,NaN
9,2014/15 total,2265980,NaN,NaN,NaN,NaN,NaN,NaN
10,2015/16 total,2280830,NaN,NaN,NaN,NaN,NaN,NaN
11,2016/17 total,2317880,NaN,NaN,NaN,NaN,NaN,NaN
12,2017/18 total,2343095,NaN,NaN,NaN,NaN,NaN,NaN
13,Last updated,January-19,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
2019.csv
Candidate rows: []

================================================================================
2020-2025.csv

Candidate rows: [8, 9, 10, 11, 12, 13, 16, 32, 33, 34]

,Title,"HE student enrolments by CAH level 1 subject, sex, entrant marker, level of study, mode of study and country of HE provider",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
5,Data file canonical link,https://www.hesa.ac.uk/data-and-analysis/sb273...,NaN,NaN,NaN,NaN,NaN,NaN
6,Licence,Creative Commons Attribution 4.0 International...,NaN,NaN,NaN,NaN,NaN,NaN
7,Code page,Unicode UTF-8,NaN,NaN,NaN,NaN,NaN,NaN
8,Disclaimer,Please note that this data includes rounded to...,NaN,NaN,NaN,NaN,NaN,NaN
9,2020/21 total,2747200,NaN,NaN,NaN,NaN,NaN,NaN
10,2021/22 total,2857855,NaN,NaN,NaN,NaN,NaN,NaN
11,2022/23 total,2937285,NaN,NaN,NaN,NaN,NaN,NaN
12,2023/24 total,2900240,NaN,NaN,NaN,NaN,NaN,NaN
13,2024/25 total,2863180,NaN,NaN,NaN,NaN,NaN,NaN
14,Last updated,Jan-26,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Build 2019-style grouped tables per year from each UK file

from io import StringIO

import re



target_columns = [

    "England",

    "Wales",

    "Scotland",

    "Northern Ireland",

    "Other UK",

    "Total UK",

]





def clean_subject_label(value: str) -> str:

    text = str(value).strip()

    match = re.match(r"^\((\d+)\)\s*(.*)$", text)

    if match:

        return f"{int(match.group(1)):02d} {match.group(2).strip()}"

    return text





def parse_2019_style_file(file_path: Path) -> dict:

    lines = file_path.read_text(encoding="utf-8-sig").splitlines()



    year_line = next((line for line in lines if line.startswith("Academic year,")), None)

    year_value = "2019/20"

    if year_line:

        parts = [part.strip().strip('"') for part in year_line.split(",")]

        if len(parts) > 1 and parts[1]:

            year_value = parts[1]



    header_idx = next((i for i, line in enumerate(lines) if line.startswith('"Subject of study"')), None)

    if header_idx is None:

        raise ValueError(f"Could not locate 'Subject of study' header in {file_path.name}")



    table_text = "\n".join(lines[header_idx:])

    df = pd.read_csv(StringIO(table_text), dtype=str)



    df = df.rename(columns={"Subject of study": "Subject"})

    for col in df.columns:

        if col != "Subject":

            df[col] = pd.to_numeric(df[col].astype(str).str.replace(",", "", regex=False), errors="coerce")



    year_table = df[["Subject"] + [col for col in target_columns if col in df.columns]].copy()

    for col in target_columns:

        if col not in year_table.columns:

            year_table[col] = pd.NA

    year_table = year_table[["Subject"] + target_columns]



    return {year_value: year_table}





def parse_long_file(file_path: Path) -> dict:

    raw = pd.read_csv(file_path, header=None, dtype=str)

    header_candidates = ["Subject Area", "CAH level 1"]

    header_idx = None

    for candidate in header_candidates:

        found = raw[raw.iloc[:, 0].astype(str).str.strip() == candidate]

        if not found.empty:

            header_idx = int(found.index[0])

            break



    if header_idx is None:

        raise ValueError(f"Could not locate long-table header in {file_path.name}")



    header_values = [str(value).strip() for value in raw.iloc[header_idx].tolist()]

    data = pd.read_csv(file_path, skiprows=header_idx + 1, header=None, names=header_values, dtype=str)

    data = data.dropna(how="all")



    subject_col = next((col for col in data.columns if "subject" in str(col).lower() or "cah level" in str(col).lower()), None)

    country_col = next((col for col in data.columns if "country" in str(col).lower()), None)

    sex_col = next((col for col in data.columns if str(col).lower().strip() == "sex"), None)

    year_col = next((col for col in data.columns if "academic year" in str(col).lower()), None)

    number_col = next((col for col in data.columns if str(col).lower().strip() == "number"), None)

    entrant_col = next((col for col in data.columns if "entrant marker" in str(col).lower() or "first year marker" in str(col).lower()), None)

    level_col = next((col for col in data.columns if "level of study" in str(col).lower()), None)

    mode_col = next((col for col in data.columns if "mode of study" in str(col).lower()), None)



    required = [subject_col, country_col, sex_col, year_col, number_col]

    if any(col is None for col in required):

        raise ValueError(f"Missing required columns in {file_path.name}. Found columns: {list(data.columns)}")



    filtered = data.copy()

    if entrant_col:

        filtered = filtered[filtered[entrant_col].astype(str).str.strip() == "All"]

    if level_col:

        filtered = filtered[filtered[level_col].astype(str).str.strip() == "All"]

    if mode_col:

        filtered = filtered[filtered[mode_col].astype(str).str.strip() == "All"]

    filtered = filtered[filtered[sex_col].astype(str).str.strip() == "Total"]



    filtered[subject_col] = filtered[subject_col].map(clean_subject_label)

    filtered[number_col] = pd.to_numeric(filtered[number_col].astype(str).str.replace(",", "", regex=False), errors="coerce")



    year_tables = {}

    for year_value, year_df in filtered.groupby(year_col):

        pivot = (

            year_df

            .pivot_table(index=subject_col, columns=country_col, values=number_col, aggfunc="sum")

            .reset_index()

            .rename(columns={subject_col: "Subject", "All": "Total UK"})

        )



        for col in target_columns:

            if col not in pivot.columns:

                pivot[col] = pd.NA



        pivot = pivot[["Subject"] + target_columns]

        pivot = pivot.sort_values("Subject").reset_index(drop=True)

        year_tables[str(year_value).strip()] = pivot



    return year_tables





uk_grouped_tables_by_year = {}



for file_path in csv_files:

    if file_path.name == "2019.csv":

        parsed = parse_2019_style_file(file_path)

    else:

        parsed = parse_long_file(file_path)



    for year_key, year_table in parsed.items():

        uk_grouped_tables_by_year[year_key] = year_table



ordered_years = sorted(uk_grouped_tables_by_year.keys())

uk_grouped_comparison_df = pd.concat(

    [

        uk_grouped_tables_by_year[year].assign(AcademicYear=year)

        for year in ordered_years

    ],

    ignore_index=True,

)



print(f"Built grouped tables for {len(ordered_years)} years:")

print(", ".join(ordered_years))



for year in ordered_years:

    print("\n" + "=" * 80)

    print(f"Academic year: {year}")

    display(uk_grouped_tables_by_year[year])

Built grouped tables for 12 years:
2013/14, 2014/15, 2015/16, 2016/17, 2017/18, 2018/19, 2019/20, 2020/21, 2021/22, 2022/23, 2023/24, 2024/25

================================================================================
Academic year: 2013/14

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,"(A) Architecture, building & planning",40280.0,1940.0,5245.0,1695.0,<NA>,49160.0
1,(B) Social studies,175820.0,10010.0,19685.0,5065.0,<NA>,210585.0
2,(C) Law,74715.0,4185.0,8300.0,2030.0,<NA>,89230.0
3,(D) Business & administrative studies,274290.0,21665.0,32305.0,8335.0,<NA>,336600.0
4,(E) Mass communications & documentation,42955.0,2400.0,3175.0,990.0,<NA>,49525.0
5,(F) Languages,95315.0,8090.0,12180.0,2080.0,<NA>,117665.0
6,(G) Historical & philosophical studies,72660.0,4830.0,10595.0,1530.0,<NA>,89620.0
7,(H) Creative arts & design,146400.0,9140.0,11175.0,2140.0,<NA>,168855.0
8,(I) Education,139870.0,13110.0,13275.0,6770.0,<NA>,173025.0
9,(J) Combined,38220.0,5690.0,10840.0,1890.0,<NA>,56635.0
10,01 Medicine & dentistry,53440.0,4055.0,7745.0,2085.0,<NA>,67325.0
11,02 Subjects allied to medicine,224555.0,12515.0,28440.0,7740.0,<NA>,273245.0
12,03 Biological sciences,167845.0,15150.0,20980.0,3590.0,<NA>,207560.0
13,04 Veterinary science,4395.0,NaN,1540.0,NaN,<NA>,5935.0
14,05 Agriculture & related subjects,14740.0,1290.0,1750.0,580.0,<NA>,18360.0
15,06 Physical sciences,75165.0,5570.0,10760.0,1820.0,<NA>,93320.0
16,07 Mathematical sciences,36330.0,1595.0,3770.0,530.0,<NA>,42230.0
17,08 Computer science,72205.0,5640.0,9840.0,3890.0,<NA>,91580.0
18,09 Engineering & technology,125925.0,10260.0,19195.0,3630.0,<NA>,159010.0
19,Total,1875125.0,137135.0,230805.0,56395.0,<NA>,2299460.0
20,Total - Non-science subject areas,1060250.0,79120.0,121535.0,30835.0,<NA>,1291735.0
21,Total - Science subject areas,814875.0,58015.0,109270.0,25565.0,<NA>,1007725.0

================================================================================
Academic year: 2014/15

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,"(A) Architecture, building & planning",39225.0,1910.0,5530.0,1590.0,<NA>,48255.0
1,(B) Social studies,173380.0,9690.0,20095.0,4830.0,<NA>,208000.0
2,(C) Law,73425.0,4015.0,8090.0,2075.0,<NA>,87605.0
3,(D) Business & administrative studies,266030.0,19860.0,32640.0,8270.0,<NA>,326800.0
4,(E) Mass communications & documentation,42045.0,2360.0,3360.0,840.0,<NA>,48610.0
5,(F) Languages,90470.0,7590.0,11385.0,1895.0,<NA>,111340.0
6,(G) Historical & philosophical studies,69750.0,4495.0,10565.0,1520.0,<NA>,86330.0
7,(H) Creative arts & design,144610.0,8590.0,11405.0,2325.0,<NA>,166930.0
8,(I) Education,131905.0,12060.0,13680.0,6750.0,<NA>,164390.0
9,(J) Combined,32605.0,5550.0,9190.0,1850.0,<NA>,49200.0
10,01 Medicine & dentistry,52365.0,3850.0,7710.0,2075.0,<NA>,66000.0
11,02 Subjects allied to medicine,226715.0,12600.0,28280.0,7745.0,<NA>,275345.0
12,03 Biological sciences,169900.0,15990.0,21625.0,3845.0,<NA>,211360.0
13,04 Veterinary science,4345.0,NaN,1555.0,NaN,<NA>,5900.0
14,05 Agriculture & related subjects,15355.0,1355.0,1835.0,655.0,<NA>,19205.0
15,06 Physical sciences,75255.0,5680.0,11085.0,1740.0,<NA>,93760.0
16,07 Mathematical sciences,36195.0,1610.0,4040.0,560.0,<NA>,42405.0
17,08 Computer science,73360.0,5360.0,10360.0,4150.0,<NA>,93230.0
18,09 Engineering & technology,127050.0,10400.0,20135.0,3730.0,<NA>,161315.0
19,Total,1844000.0,132965.0,232570.0,56445.0,<NA>,2265980.0
20,Total - Non-science subject areas,1024225.0,74215.0,120410.0,30355.0,<NA>,1249205.0
21,Total - Science subject areas,819775.0,58750.0,112160.0,26090.0,<NA>,1016775.0

================================================================================
Academic year: 2015/16

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,"(A) Architecture, building & planning",40190.0,2050.0,5600.0,1545.0,<NA>,49385.0
1,(B) Social studies,178305.0,10550.0,20510.0,4785.0,<NA>,214145.0
2,(C) Law,74215.0,4060.0,8280.0,2110.0,<NA>,88665.0
3,(D) Business & administrative studies,269120.0,17110.0,32580.0,7690.0,<NA>,326500.0
4,(E) Mass communications & documentation,42880.0,2295.0,3350.0,790.0,<NA>,49320.0
5,(F) Languages,87815.0,7500.0,11155.0,1890.0,<NA>,108355.0
6,(G) Historical & philosophical studies,68775.0,4370.0,10815.0,1415.0,<NA>,85375.0
7,(H) Creative arts & design,147190.0,8465.0,11900.0,2270.0,<NA>,169825.0
8,(I) Education,124395.0,11435.0,13905.0,6415.0,<NA>,156150.0
9,(J) Combined,28175.0,3930.0,8320.0,1500.0,<NA>,41920.0
10,01 Medicine & dentistry,52235.0,3565.0,7655.0,2095.0,<NA>,65550.0
11,02 Subjects allied to medicine,233670.0,14170.0,29130.0,7960.0,<NA>,284935.0
12,03 Biological sciences,176195.0,15465.0,21850.0,3800.0,<NA>,217310.0
13,04 Veterinary science,5255.0,NaN,1520.0,NaN,<NA>,6775.0
14,05 Agriculture & related subjects,15090.0,1350.0,1975.0,610.0,<NA>,19025.0
15,06 Physical sciences,75680.0,5815.0,11665.0,1760.0,<NA>,94920.0
16,07 Mathematical sciences,36575.0,1605.0,4405.0,575.0,<NA>,43155.0
17,08 Computer science,76125.0,5165.0,10690.0,4285.0,<NA>,96260.0
18,09 Engineering & technology,129465.0,9785.0,20250.0,3755.0,<NA>,163255.0
19,Total,1861345.0,128675.0,235565.0,55245.0,<NA>,2280830.0
20,Total - Non-science subject areas,1020865.0,69710.0,120825.0,28860.0,<NA>,1240255.0
21,Total - Science subject areas,840485.0,58965.0,114740.0,26380.0,<NA>,1040570.0

================================================================================
Academic year: 2016/17

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,"(A) Architecture, building & planning",41760.0,2110.0,5820.0,1575.0,<NA>,51265.0
1,(B) Social studies,185455.0,11295.0,20335.0,4625.0,<NA>,221710.0
2,(C) Law,74915.0,4140.0,8425.0,2250.0,<NA>,89730.0
3,(D) Business & administrative studies,276855.0,16590.0,32460.0,7520.0,<NA>,333425.0
4,(E) Mass communications & documentation,43655.0,2470.0,3495.0,805.0,<NA>,50420.0
5,(F) Languages,86070.0,7405.0,11770.0,1795.0,<NA>,107040.0
6,(G) Historical & philosophical studies,68390.0,4500.0,11285.0,1280.0,<NA>,85455.0
7,(H) Creative arts & design,152940.0,8390.0,12215.0,2155.0,<NA>,175700.0
8,(I) Education,119435.0,10070.0,15240.0,6310.0,<NA>,151060.0
9,(J) Combined,25305.0,4020.0,8165.0,1145.0,<NA>,38640.0
10,01 Medicine & dentistry,52020.0,3370.0,7640.0,2085.0,<NA>,65110.0
11,02 Subjects allied to medicine,237615.0,14480.0,30165.0,8515.0,<NA>,290770.0
12,03 Biological sciences,183615.0,16285.0,22935.0,3565.0,<NA>,226395.0
13,04 Veterinary science,5605.0,NaN,1545.0,NaN,<NA>,7145.0
14,05 Agriculture & related subjects,14605.0,1345.0,2125.0,585.0,<NA>,18655.0
15,06 Physical sciences,75810.0,5885.0,11770.0,1705.0,<NA>,95170.0
16,07 Mathematical sciences,37350.0,1630.0,4330.0,570.0,<NA>,43880.0
17,08 Computer science,79905.0,5400.0,11600.0,4240.0,<NA>,101145.0
18,09 Engineering & technology,130685.0,10015.0,20620.0,3835.0,<NA>,165155.0
19,Total,1891980.0,129395.0,241935.0,54570.0,<NA>,2317880.0
20,Total - Non-science subject areas,1033020.0,68880.0,123390.0,27885.0,<NA>,1253175.0
21,Total - Science subject areas,858960.0,60515.0,118540.0,26680.0,<NA>,1064700.0

================================================================================
Academic year: 2017/18

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,"(A) Architecture, building & planning",43720.0,2135.0,6150.0,1615.0,<NA>,53620.0
1,(B) Social studies,191935.0,11570.0,21205.0,4650.0,<NA>,229360.0
2,(C) Law,76995.0,4210.0,8755.0,2210.0,<NA>,92165.0
3,(D) Business & administrative studies,286975.0,15280.0,33215.0,7500.0,<NA>,342970.0
4,(E) Mass communications & documentation,44565.0,2455.0,3440.0,900.0,<NA>,51360.0
5,(F) Languages,81905.0,7560.0,12375.0,1700.0,<NA>,103545.0
6,(G) Historical & philosophical studies,66895.0,4270.0,11730.0,1220.0,<NA>,84115.0
7,(H) Creative arts & design,155630.0,8580.0,12170.0,2035.0,<NA>,178415.0
8,(I) Education,114950.0,8505.0,15635.0,6365.0,<NA>,145445.0
9,(J) Combined,22560.0,5380.0,6300.0,885.0,<NA>,35120.0
10,01 Medicine & dentistry,52885.0,3180.0,7655.0,2160.0,<NA>,65875.0
11,02 Subjects allied to medicine,233525.0,15255.0,30690.0,8595.0,<NA>,288065.0
12,03 Biological sciences,189270.0,17060.0,24020.0,3620.0,<NA>,233970.0
13,04 Veterinary science,6310.0,NaN,1550.0,NaN,<NA>,7860.0
14,05 Agriculture & related subjects,14545.0,1315.0,2345.0,475.0,<NA>,18680.0
15,06 Physical sciences,76320.0,5790.0,11890.0,1715.0,<NA>,95720.0
16,07 Mathematical sciences,37730.0,1600.0,4665.0,585.0,<NA>,44575.0
17,08 Computer science,84665.0,5585.0,12640.0,4360.0,<NA>,107250.0
18,09 Engineering & technology,130560.0,9865.0,20670.0,3875.0,<NA>,164975.0
19,Total,1911940.0,129585.0,247110.0,54460.0,<NA>,2343095.0
20,Total - Non-science subject areas,1042410.0,67800.0,124825.0,27465.0,<NA>,1262500.0
21,Total - Science subject areas,869530.0,61785.0,122280.0,26995.0,<NA>,1080590.0

================================================================================
Academic year: 2018/19

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,"(A) Architecture, building & planning",45235.0,2215.0,6380.0,1515.0,<NA>,55345.0
1,(B) Social studies,198700.0,12335.0,21710.0,4735.0,<NA>,237480.0
2,(C) Law,79080.0,4415.0,9280.0,2480.0,<NA>,95260.0
3,(D) Business & administrative studies,300685.0,16015.0,34030.0,7745.0,<NA>,358480.0
4,(E) Mass communications & documentation,44395.0,2540.0,3405.0,970.0,<NA>,51310.0
5,(F) Languages,77930.0,7230.0,12620.0,1590.0,<NA>,99365.0
6,(G) Historical & philosophical studies,65110.0,4060.0,11650.0,1145.0,<NA>,81965.0
7,(H) Creative arts & design,158475.0,8725.0,12575.0,2055.0,<NA>,181830.0
8,(I) Education,112280.0,8155.0,16365.0,6025.0,<NA>,142825.0
9,(J) Combined,19580.0,5255.0,6065.0,870.0,<NA>,31765.0
10,01 Medicine & dentistry,54625.0,3210.0,7795.0,2130.0,<NA>,67755.0
11,02 Subjects allied to medicine,234005.0,15750.0,31175.0,9525.0,<NA>,290445.0
12,03 Biological sciences,195705.0,17545.0,24765.0,3745.0,<NA>,241755.0
13,04 Veterinary science,6770.0,NaN,1630.0,NaN,<NA>,8400.0
14,05 Agriculture & related subjects,15150.0,1290.0,2370.0,510.0,<NA>,19320.0
15,06 Physical sciences,75130.0,6190.0,11810.0,1710.0,<NA>,94845.0
16,07 Mathematical sciences,38635.0,1650.0,5040.0,585.0,<NA>,45910.0
17,08 Computer science,90195.0,6135.0,13960.0,4440.0,<NA>,114730.0
18,09 Engineering & technology,130855.0,9490.0,20855.0,3980.0,<NA>,165180.0
19,Total,1942535.0,132205.0,253475.0,55755.0,<NA>,2383970.0
20,Total - Non-science subject areas,1056235.0,68730.0,127700.0,27610.0,<NA>,1280280.0
21,Total - Science subject areas,886295.0,63475.0,125775.0,28145.0,<NA>,1103690.0

================================================================================
Academic year: 2019/20

,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,01 Medicine and dentistry,48230,2445,5105,2440,135,58350
1,02 Subjects allied to medicine,215675,14610,25610,9985,370,266245
2,03 Biological and sport sciences,80840,5455,8005,2590,310,97200
3,04 Psychology,89465,5525,7510,2295,245,105040
4,05 Veterinary sciences,7100,440,910,265,25,8740
5,"06 Agriculture, food and related studies",10300,1090,2045,535,45,14010
6,07 Physical sciences,44565,2540,5345,1225,125,53795
7,09 Mathematical sciences,28600,1370,2685,895,90,33640
8,10 Engineering and technology,91370,5955,14150,3915,225,115615
9,11 Computing,75790,5035,9940,5285,170,96220
10,"13 Architecture, building and planning",36505,1970,4170,1580,85,44315
11,"26 Geography, earth and environmental studies ...",21800,1460,2465,860,95,26680
12,Total science CAH level 1,750235,47885,87945,31875,1915,919855
13,15 Social sciences,176635,12175,15980,5915,380,211085
14,16 Law,81895,4845,6855,2490,250,96340
15,17 Business and management,214955,10470,20180,7405,565,253580
16,19 Language and area studies,64795,3815,6870,2040,235,77750
17,"20 Historical, philosophical and religious stu...",63455,3130,6065,1460,235,74345
18,22 Education and teaching,90995,7345,13360,5650,185,117540
19,23 Combined and general studies,23260,4200,7715,1390,30,36595
20,"24 Media, journalism and communications",27355,1425,2515,1075,100,32475
21,"25 Design, and creative and performing arts",125135,7890,9220,3205,500,145950
22,"26 Geography, earth and environmental studies ...",8820,415,495,130,40,9900
23,Total non-science CAH level 1,877300,55710,89250,30770,2530,1055560
24,Total,1627535,103595,177190,62645,4450,1975415

================================================================================
Academic year: 2020/21

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,01 Medicine and dentistry,61550,3675,9595,2230,<NA>,77055
1,02 Subjects allied to medicine,271880,17345,34255,10295,<NA>,333780
2,03 Biological and sport sciences,91840,10550,13165,2005,<NA>,117560
3,04 Psychology,112515,8195,12190,2185,<NA>,135080
4,05 Veterinary sciences,9240,95,2240,0,<NA>,11575
5,"06 Agriculture, food and related studies",14005,1310,2755,465,<NA>,18535
6,07 Physical sciences,55175,3260,8660,1100,<NA>,68195
7,09 Mathematical sciences,40410,1685,5695,740,<NA>,48530
8,10 Engineering and technology,146880,10205,21850,4230,<NA>,183165
9,11 Computing,121805,9115,17380,5540,<NA>,153840
10,"13 Architecture, building and planning",51135,2445,6935,1730,<NA>,62235
11,15 Social sciences,234225,16485,25945,5940,<NA>,282600
12,16 Law,119590,6405,9855,2290,<NA>,138140
13,17 Business and management,404390,20890,39340,10540,<NA>,475160
14,19 Language and area studies,72755,5695,12555,1625,<NA>,92635
15,"20 Historical, philosophical and religious stu...",68930,3910,12120,1025,<NA>,85990
16,22 Education and teaching,108985,7745,16255,3045,<NA>,136035
17,23 Combined and general studies,28690,3735,10060,2050,<NA>,44535
18,"24 Media, journalism and communications",39985,2525,4205,925,<NA>,47640
19,"25 Design, and creative and performing arts",168465,7040,12405,2275,<NA>,190185
20,"26 Geography, earth and environmental studies ...",25190,2160,4240,810,<NA>,32400
21,"26 Geography, earth and environmental studies ...",10345,700,1175,115,<NA>,12330
22,Total,2257990,145170,282875,61165,<NA>,2747200
23,Total non-science CAH level 1,1256365,75135,143910,29840,<NA>,1505250
24,Total science CAH level 1,1001625,70030,138960,31330,<NA>,1241950

================================================================================
Academic year: 2021/22

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,01 Medicine and dentistry,64770,3740,10655,2500,<NA>,81665
1,02 Subjects allied to medicine,296070,18005,36370,10900,<NA>,361340
2,03 Biological and sport sciences,91565,10615,13370,1960,<NA>,117510
3,04 Psychology,116475,8720,13025,2205,<NA>,140425
4,05 Veterinary sciences,9745,120,2275,0,<NA>,12140
5,"06 Agriculture, food and related studies",15215,1200,2805,440,<NA>,19660
6,07 Physical sciences,54310,3015,8805,1075,<NA>,67205
7,09 Mathematical sciences,38870,1665,5970,635,<NA>,47140
8,10 Engineering and technology,149605,10010,22035,4075,<NA>,185725
9,11 Computing,131065,9795,18355,5045,<NA>,164260
10,"13 Architecture, building and planning",52130,2500,7230,1765,<NA>,63630
11,15 Social sciences,238075,15140,27060,5955,<NA>,286225
12,16 Law,120920,8835,10230,2325,<NA>,142315
13,17 Business and management,450245,22710,45020,12610,<NA>,530580
14,19 Language and area studies,68300,5150,12825,1525,<NA>,87800
15,"20 Historical, philosophical and religious stu...",65845,3845,12410,980,<NA>,83085
16,22 Education and teaching,107530,7700,17870,2885,<NA>,135980
17,23 Combined and general studies,29010,3935,10880,3820,<NA>,47645
18,"24 Media, journalism and communications",39920,2670,4610,960,<NA>,48155
19,"25 Design, and creative and performing arts",167960,6830,13025,2115,<NA>,189930
20,"26 Geography, earth and environmental studies ...",25085,2125,5240,765,<NA>,33220
21,"26 Geography, earth and environmental studies ...",10190,725,1170,140,<NA>,12225
22,Total,2342905,149045,301230,64675,<NA>,2857855
23,Total non-science CAH level 1,1297995,77540,155100,33305,<NA>,1563945
24,Total science CAH level 1,1044905,71505,146130,31370,<NA>,1293910

================================================================================
Academic year: 2022/23

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,01 Medicine and dentistry,68005,3525,9985,2715,<NA>,84230
1,02 Subjects allied to medicine,303995,19115,35345,11080,<NA>,369535
2,03 Biological and sport sciences,92570,10370,12785,2030,<NA>,117755
3,04 Psychology,118035,8410,12515,2145,<NA>,141105
4,05 Veterinary sciences,10050,140,2085,0,<NA>,12280
5,"06 Agriculture, food and related studies",15605,1340,2480,380,<NA>,19805
6,07 Physical sciences,53910,2755,8530,1110,<NA>,66305
7,09 Mathematical sciences,38375,1560,5575,585,<NA>,46090
8,10 Engineering and technology,150900,9605,21280,4090,<NA>,185875
9,11 Computing,147425,9755,18350,5170,<NA>,180695
10,"13 Architecture, building and planning",55440,2490,7190,1910,<NA>,67035
11,15 Social sciences,237930,14730,26890,6035,<NA>,285585
12,16 Law,124685,9420,9935,2550,<NA>,146595
13,17 Business and management,500955,26670,45025,14420,<NA>,587075
14,19 Language and area studies,66100,4970,12325,1515,<NA>,84910
15,"20 Historical, philosophical and religious stu...",62295,3885,11890,970,<NA>,79040
16,22 Education and teaching,102905,8140,16095,2865,<NA>,130005
17,23 Combined and general studies,31495,5250,9990,4070,<NA>,50805
18,"24 Media, journalism and communications",39995,2705,4820,915,<NA>,48435
19,"25 Design, and creative and performing arts",166775,6545,13175,2035,<NA>,188535
20,"26 Geography, earth and environmental studies ...",25325,2265,4910,770,<NA>,33275
21,"26 Geography, earth and environmental studies ...",10375,745,1060,145,<NA>,12325
22,Total,2423140,154385,292240,67515,<NA>,2937285
23,Total non-science CAH level 1,1343510,83060,151205,35525,<NA>,1613300
24,Total science CAH level 1,1079630,71325,141035,31995,<NA>,1323985

================================================================================
Academic year: 2023/24

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,01 Medicine and dentistry,68535,3575,10595,2525,<NA>,85235
1,02 Subjects allied to medicine,302835,18445,33305,10640,<NA>,365225
2,03 Biological and sport sciences,89650,10550,12810,2125,<NA>,115135
3,04 Psychology,116745,8385,12495,2245,<NA>,139870
4,05 Veterinary sciences,10565,150,2150,0,<NA>,12870
5,"06 Agriculture, food and related studies",15690,1155,2325,370,<NA>,19540
6,07 Physical sciences,52645,2785,8375,1135,<NA>,64940
7,09 Mathematical sciences,37465,1675,5265,580,<NA>,44990
8,10 Engineering and technology,144960,9290,20370,4170,<NA>,178790
9,11 Computing,158300,9715,18435,5410,<NA>,191865
10,"13 Architecture, building and planning",55445,2635,6310,1870,<NA>,66265
11,15 Social sciences,232910,15135,25560,5730,<NA>,279330
12,16 Law,123500,8955,9755,2540,<NA>,144750
13,17 Business and management,514815,25100,40975,13735,<NA>,594625
14,19 Language and area studies,61580,4760,12280,1470,<NA>,80085
15,"20 Historical, philosophical and religious stu...",60155,4135,12010,1010,<NA>,77305
16,22 Education and teaching,93070,7885,15105,2825,<NA>,118885
17,23 Combined and general studies,29960,4135,9395,1445,<NA>,44935
18,"24 Media, journalism and communications",39340,2720,4570,945,<NA>,47580
19,"25 Design, and creative and performing arts",160915,6155,13145,2120,<NA>,182335
20,"26 Geography, earth and environmental studies ...",24980,2530,5135,810,<NA>,33450
21,"26 Geography, earth and environmental studies ...",10175,800,1090,170,<NA>,12235
22,Total,2404235,150680,281455,63875,<NA>,2900240
23,Total non-science CAH level 1,1326415,79780,143880,31995,<NA>,1582070
24,Total science CAH level 1,1077820,70895,137575,31880,<NA>,1318170

================================================================================
Academic year: 2024/25

Country of HE provider,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,01 Medicine and dentistry,68725,3680,10400,2540,<NA>,85345
1,02 Subjects allied to medicine,298675,18055,32085,11540,<NA>,360360
2,03 Biological and sport sciences,85730,10320,13115,2210,<NA>,111380
3,04 Psychology,115720,8310,12030,2230,<NA>,138290
4,05 Veterinary sciences,10555,185,2020,0,<NA>,12760
5,"06 Agriculture, food and related studies",14490,1020,2155,295,<NA>,17960
6,07 Physical sciences,52385,2680,8110,1145,<NA>,64325
7,09 Mathematical sciences,37255,1580,5310,580,<NA>,44725
8,10 Engineering and technology,143725,8795,19755,4255,<NA>,176530
9,11 Computing,169810,9495,20325,6360,<NA>,205990
10,"13 Architecture, building and planning",57290,2470,5890,1825,<NA>,67475
11,15 Social sciences,229200,15780,25115,5805,<NA>,275900
12,16 Law,123770,8170,9950,2635,<NA>,144525
13,17 Business and management,515240,21415,37780,12285,<NA>,586710
14,19 Language and area studies,58020,4440,11280,1620,<NA>,75355
15,"20 Historical, philosophical and religious stu...",59860,3835,11750,1050,<NA>,76495
16,22 Education and teaching,84770,7720,14630,2760,<NA>,109885
17,23 Combined and general studies,26385,3930,6400,2485,<NA>,39200
18,"24 Media, journalism and communications",38395,2505,5400,955,<NA>,47255
19,"25 Design, and creative and performing arts",156900,6230,13530,2095,<NA>,178755
20,"26 Geography, earth and environmental studies ...",24205,2390,4530,860,<NA>,31985
21,"26 Geography, earth and environmental studies ...",9930,825,1050,165,<NA>,11970
22,Total,2381040,143825,272615,65695,<NA>,2863180
23,Total non-science CAH level 1,1302465,74850,136885,31860,<NA>,1546060
24,Total science CAH level 1,1078580,68975,135735,33835,<NA>,1317120

In [5]:
# Export grouped UK enrollment outputs

output_candidates = [

    Path.cwd() / "data" / "clean" / "uk_grouped",

    Path.cwd().parent / "data" / "clean" / "uk_grouped",

]

uk_output_dir = next((path for path in output_candidates if path.parent.exists()), output_candidates[0])

uk_output_dir.mkdir(parents=True, exist_ok=True)



for year, table in uk_grouped_tables_by_year.items():

    safe_year = year.replace("/", "-")

    table.to_csv(uk_output_dir / f"UK_enrollments_grouped_{safe_year}.csv", index=False)



uk_grouped_comparison_df.to_csv(uk_output_dir / "UK_enrollments_grouped_comparison_all_years.csv", index=False)



print(f"Exported per-year files to: {uk_output_dir}")

print(f"Combined comparison file: {uk_output_dir / 'UK_enrollments_grouped_comparison_all_years.csv'}")

Exported per-year files to: C:\Users\neddp\ECC3479-Project-JRGS\data\clean\uk_grouped
Combined comparison file: C:\Users\neddp\ECC3479-Project-JRGS\data\clean\uk_grouped\UK_enrollments_grouped_comparison_all_years.csv

In [6]:
# Add AUS-aligned categorykey to UK grouped tables

import re



uk_subjectcode_to_categorykey = {

    1: 6,   # Medicine and dentistry -> Health

    2: 6,   # Subjects allied to medicine -> Health

    3: 1,   # Biological and sport sciences -> Natural & Physical Science

    4: 9,   # Psychology -> Society & Culture

    5: 6,   # Veterinary sciences -> Health

    6: 5,   # Agriculture, food and related studies -> Environment & Related

    7: 1,   # Physical sciences -> Natural & Physical Science

    9: 1,   # Mathematical sciences -> Natural & Physical Science

    10: 3,  # Engineering and technology -> Engineering & Related Tech

    11: 2,  # Computing -> Information Technology

    13: 4,  # Architecture, building and planning -> Architecture & Building

    15: 9,  # Social sciences -> Society & Culture

    16: 9,  # Law -> Society & Culture

    17: 8,  # Business and management -> Management & Commerce

    19: 9,  # Language and area studies -> Society & Culture

    20: 9,  # Historical, philosophical and religious studies -> Society & Culture

    22: 7,  # Education and teaching -> Education

    23: 11, # Combined and general studies -> Others

    24: 9,  # Media, journalism and communications -> Society & Culture

    25: 10, # Design, and creative and performing arts -> Creative Arts

    26: 5,  # Geography, earth and environmental studies -> Environment & Related

}





def extract_subject_code(subject_value: str):

    text = str(subject_value).strip()

    if text.lower().startswith("total"):

        return "TOTAL"



    match = re.match(r"^(\d{1,2})\b", text)

    if match:

        return int(match.group(1))



    match = re.match(r"^\((\d{1,2})\)", text)

    if match:

        return int(match.group(1))



    return None





def map_categorykey(subject_value: str):

    code = extract_subject_code(subject_value)

    if code == "TOTAL":

        return 99

    if code in uk_subjectcode_to_categorykey:

        return uk_subjectcode_to_categorykey[code]

    return 11





uk_grouped_tables_with_categorykey_by_year = {}

for year, table in uk_grouped_tables_by_year.items():

    enriched = table.copy()

    enriched["categorykey"] = enriched["Subject"].map(map_categorykey).astype("Int64")

    enriched = enriched.sort_values(["categorykey", "Subject"]).reset_index(drop=True)

    uk_grouped_tables_with_categorykey_by_year[year] = enriched



uk_grouped_comparison_with_categorykey_df = pd.concat(

    [

        uk_grouped_tables_with_categorykey_by_year[year].assign(AcademicYear=year)

        for year in sorted(uk_grouped_tables_with_categorykey_by_year.keys())

    ],

    ignore_index=True,

)



print("Added 'categorykey' to UK grouped tables using AUS key system (1..11, 99).")

print("Preview: 2019/20")

if "2019/20" in uk_grouped_tables_with_categorykey_by_year:

    display(uk_grouped_tables_with_categorykey_by_year["2019/20"])

else:

    first_year = sorted(uk_grouped_tables_with_categorykey_by_year.keys())[0]

    display(uk_grouped_tables_with_categorykey_by_year[first_year])

Added 'categorykey' to UK grouped tables using AUS key system (1..11, 99).

Preview: 2019/20

,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK,categorykey
0,03 Biological and sport sciences,80840,5455,8005,2590,310,97200,1
1,07 Physical sciences,44565,2540,5345,1225,125,53795,1
2,09 Mathematical sciences,28600,1370,2685,895,90,33640,1
3,11 Computing,75790,5035,9940,5285,170,96220,2
4,10 Engineering and technology,91370,5955,14150,3915,225,115615,3
5,"13 Architecture, building and planning",36505,1970,4170,1580,85,44315,4
6,"06 Agriculture, food and related studies",10300,1090,2045,535,45,14010,5
7,"26 Geography, earth and environmental studies ...",21800,1460,2465,860,95,26680,5
8,"26 Geography, earth and environmental studies ...",8820,415,495,130,40,9900,5
9,01 Medicine and dentistry,48230,2445,5105,2440,135,58350,6
10,02 Subjects allied to medicine,215675,14610,25610,9985,370,266245,6
11,05 Veterinary sciences,7100,440,910,265,25,8740,6
12,22 Education and teaching,90995,7345,13360,5650,185,117540,7
13,17 Business and management,214955,10470,20180,7405,565,253580,8
14,04 Psychology,89465,5525,7510,2295,245,105040,9
15,15 Social sciences,176635,12175,15980,5915,380,211085,9
16,16 Law,81895,4845,6855,2490,250,96340,9
17,19 Language and area studies,64795,3815,6870,2040,235,77750,9
18,"20 Historical, philosophical and religious stu...",63455,3130,6065,1460,235,74345,9
19,"24 Media, journalism and communications",27355,1425,2515,1075,100,32475,9
20,"25 Design, and creative and performing arts",125135,7890,9220,3205,500,145950,10
21,23 Combined and general studies,23260,4200,7715,1390,30,36595,11
22,Total,1627535,103595,177190,62645,4450,1975415,99
23,Total non-science CAH level 1,877300,55710,89250,30770,2530,1055560,99
24,Total science CAH level 1,750235,47885,87945,31875,1915,919855,99

In [7]:
# Export UK grouped outputs with categorykey (separate files)

uk_output_with_key_dir = uk_output_dir / "with_categorykey"

uk_output_with_key_dir.mkdir(parents=True, exist_ok=True)



for year, table in uk_grouped_tables_with_categorykey_by_year.items():

    safe_year = year.replace("/", "-")

    table.to_csv(uk_output_with_key_dir / f"UK_enrollments_grouped_{safe_year}_with_categorykey.csv", index=False)



uk_grouped_comparison_with_categorykey_df.to_csv(

    uk_output_with_key_dir / "UK_enrollments_grouped_comparison_all_years_with_categorykey.csv",

    index=False,

)



print(f"Exported UK grouped files with categorykey to: {uk_output_with_key_dir}")

Exported UK grouped files with categorykey to: C:\Users\neddp\ECC3479-Project-JRGS\data\clean\uk_grouped\with_categorykey

In [8]:
# Add Category names from AUS key system (for readability)

categorykey_to_category = {

    1: "Natural & Physical Science",

    2: "Information Technology",

    3: "Engineering & Related Tech",

    4: "Architecture & Building",

    5: "Environment & Related",

    6: "Health",

    7: "Education",

    8: "Management & Commerce",

    9: "Society & Culture",

    10: "Creative Arts",

    11: "Others",

    99: "Total",

}



uk_grouped_tables_with_category_by_year = {}

for year, table in uk_grouped_tables_with_categorykey_by_year.items():

    enriched = table.copy()

    enriched["Category"] = enriched["categorykey"].map(categorykey_to_category)

    enriched = enriched[["categorykey", "Category", "Subject", "England", "Wales", "Scotland", "Northern Ireland", "Other UK", "Total UK"]]

    enriched = enriched.sort_values(["categorykey", "Subject"]).reset_index(drop=True)

    uk_grouped_tables_with_category_by_year[year] = enriched



uk_grouped_comparison_with_category_df = pd.concat(

    [

        uk_grouped_tables_with_category_by_year[year].assign(AcademicYear=year)

        for year in sorted(uk_grouped_tables_with_category_by_year.keys())

    ],

    ignore_index=True,

)



uk_output_with_category_dir = uk_output_with_key_dir / "with_category_name"

uk_output_with_category_dir.mkdir(parents=True, exist_ok=True)



for year, table in uk_grouped_tables_with_category_by_year.items():

    safe_year = year.replace("/", "-")

    table.to_csv(uk_output_with_category_dir / f"UK_enrollments_grouped_{safe_year}_with_category.csv", index=False)



uk_grouped_comparison_with_category_df.to_csv(

    uk_output_with_category_dir / "UK_enrollments_grouped_comparison_all_years_with_category.csv",

    index=False,

)



print(f"Exported UK grouped files with Category names to: {uk_output_with_category_dir}")

print("Preview: 2019/20")

if "2019/20" in uk_grouped_tables_with_category_by_year:

    display(uk_grouped_tables_with_category_by_year["2019/20"])

else:

    first_year = sorted(uk_grouped_tables_with_category_by_year.keys())[0]

    display(uk_grouped_tables_with_category_by_year[first_year])

Exported UK grouped files with Category names to: C:\Users\neddp\ECC3479-Project-JRGS\data\clean\uk_grouped\with_categorykey\with_category_name

Preview: 2019/20

,categorykey,Category,Subject,England,Wales,Scotland,Northern Ireland,Other UK,Total UK
0,1,Natural & Physical Science,03 Biological and sport sciences,80840,5455,8005,2590,310,97200
1,1,Natural & Physical Science,07 Physical sciences,44565,2540,5345,1225,125,53795
2,1,Natural & Physical Science,09 Mathematical sciences,28600,1370,2685,895,90,33640
3,2,Information Technology,11 Computing,75790,5035,9940,5285,170,96220
4,3,Engineering & Related Tech,10 Engineering and technology,91370,5955,14150,3915,225,115615
5,4,Architecture & Building,"13 Architecture, building and planning",36505,1970,4170,1580,85,44315
6,5,Environment & Related,"06 Agriculture, food and related studies",10300,1090,2045,535,45,14010
7,5,Environment & Related,"26 Geography, earth and environmental studies ...",21800,1460,2465,860,95,26680
8,5,Environment & Related,"26 Geography, earth and environmental studies ...",8820,415,495,130,40,9900
9,6,Health,01 Medicine and dentistry,48230,2445,5105,2440,135,58350
10,6,Health,02 Subjects allied to medicine,215675,14610,25610,9985,370,266245
11,6,Health,05 Veterinary sciences,7100,440,910,265,25,8740
12,7,Education,22 Education and teaching,90995,7345,13360,5650,185,117540
13,8,Management & Commerce,17 Business and management,214955,10470,20180,7405,565,253580
14,9,Society & Culture,04 Psychology,89465,5525,7510,2295,245,105040
15,9,Society & Culture,15 Social sciences,176635,12175,15980,5915,380,211085
16,9,Society & Culture,16 Law,81895,4845,6855,2490,250,96340
17,9,Society & Culture,19 Language and area studies,64795,3815,6870,2040,235,77750
18,9,Society & Culture,"20 Historical, philosophical and religious stu...",63455,3130,6065,1460,235,74345
19,9,Society & Culture,"24 Media, journalism and communications",27355,1425,2515,1075,100,32475
20,10,Creative Arts,"25 Design, and creative and performing arts",125135,7890,9220,3205,500,145950
21,11,Others,23 Combined and general studies,23260,4200,7715,1390,30,36595
22,99,Total,Total,1627535,103595,177190,62645,4450,1975415
23,99,Total,Total non-science CAH level 1,877300,55710,89250,30770,2530,1055560
24,99,Total,Total science CAH level 1,750235,47885,87945,31875,1915,919855