In [1]:
import pandas as pd
import os

# Set the path to the data file
data_path = os.path.join('..', 'data', 'clean', 'EnrollmentsAUS_extracted.csv')

# Load the CSV file
df = pd.read_csv(data_path)

# Display the dataframe
df

                                                 text
0   Selected Higher Education Statistics | Home\nV...
1   Selected Higher Education Statistics | Home\nV...
2   Selected Higher Education Statistics | Home\nV...
3   Selected Higher Education Statistics | Home\nV...
4   Selected Higher Education Statistics | Home\nV...
5   Selected Higher Education Statistics | Home\nV...
6   Selected Higher Education Statistics | Home\nV...
7   Selected Higher Education Statistics | Home\nV...
8   Selected Higher Education Statistics | Home\nV...
9   Selected Higher Education Statistics | Home\nV...
10  Selected Higher Education Statistics | Home\nV...
11  Selected Higher Education Statistics | Home\nV...
12  Selected Higher Education Statistics | Home\nV...
13  Selected Higher Education Statistics | Home\nV...
14  Selected Higher Education Statistics | Home\nV...
15  Selected Higher Education Statistics | Home\nV...
16  Selected Higher Education Statistics | Home\nV...
17  Selected Higher Education Statistics | Home\nV...
18  Selected Higher Education Statistics | Home\nV...
19  Selected Higher Education Statistics | Home\nV...
20  Selected Higher Education Statistics | Home\nV...
21  Verified data for years 2015 to 2024 | Source:...
22  Verified data for years 2015 to 2024 | Source:...
23  Verified data for years 2015 to 2024 | Source:...
24  Verified data for years 2015 to 2024 | Source:...
25  Verified data for years 2015 to 2024 | Source:...
26  Verified data for years 2015 to 2024 | Source:...
27  Verified data for years 2015 to 2024 | Source:...
28  Verified data for years 2015 to 2024 | Source:...
29  Verified data for years 2015 to 2024 | Source:...
30  Verified data for years 2015 to 2024 | Source:...
31  Verified data for years 2015 to 2024 | Source:...
32  Verified data for years 2015 to 2024 | Source:...
33  Verified data for years 2015 to 2024 | Source:...

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

driver = webdriver.Chrome()
driver.get('https://app.powerbi.com/view?r=eyJrIjoiN2Y1ZTM1Y2YtYzYxNC00MWI0LWFhNTktYTI3NWU2OWI3NGFkIiwidCI6ImRkMGNmZDE1LTQ1NTgtNGIxMi04YmFkLWVhMjY5ODRmYzQxNyJ9')

# Wait for table to load, then extract
table = driver.find_element(By.TAG_NAME, 'table')
df = pd.read_html(table.get_attribute('outerHTML'))[0]
print(df)

driver.quit()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"table"}
  (Session info: chrome=146.0.7680.155); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff619d029c5+2ed785]
	chromedriver!GetHandleVerifier [0x7ff619a2a0d0+14e90]
	chromedriver!(No symbol) [0x7ff61978db2d]
	chromedriver!(No symbol) [0x7ff6197e6b9e]
	chromedriver!(No symbol) [0x7ff6197e6eac]
	chromedriver!(No symbol) [0x7ff619836fe7]
	chromedriver!(No symbol) [0x7ff619833b9b]
	chromedriver!(No symbol) [0x7ff6197d9298]
	chromedriver!(No symbol) [0x7ff6197da183]
	chromedriver!GetHandleVerifier [0x7ff619d2de0d+318bcd]
	chromedriver!GetHandleVerifier [0x7ff619d28588+313348]
	chromedriver!GetHandleVerifier [0x7ff619d49d7a+334b3a]
	chromedriver!GetHandleVerifier [0x7ff619a46785+31545]
	chromedriver!GetHandleVerifier [0x7ff619a4facc+3a88c]
	chromedriver!GetHandleVerifier [0x7ff619a33634+1e3f4]
	chromedriver!GetHandleVerifier [0x7ff619a337e6+1e5a6]
	chromedriver!GetHandleVerifier [0x7ff619a17e37+2bf7]
	KERNEL32!BaseThreadInitThunk [0x7ff87b3ce8d7+17]
	ntdll!RtlUserThreadStart [0x7ff87bc6c48c+2c]

In [4]:
# Display the scraped data as a formatted table
from IPython.display import display
import pandas as pd

# Show the scraped data
print("Enrollment Data from PowerBI:")
display(df)

Enrollment Data from PowerBI:

                                                 text
0   Selected Higher Education Statistics | Home\nV...
1   Selected Higher Education Statistics | Home\nV...
2   Selected Higher Education Statistics | Home\nV...
3   Selected Higher Education Statistics | Home\nV...
4   Selected Higher Education Statistics | Home\nV...
5   Selected Higher Education Statistics | Home\nV...
6   Selected Higher Education Statistics | Home\nV...
7   Selected Higher Education Statistics | Home\nV...
8   Selected Higher Education Statistics | Home\nV...
9   Selected Higher Education Statistics | Home\nV...
10  Selected Higher Education Statistics | Home\nV...
11  Selected Higher Education Statistics | Home\nV...
12  Selected Higher Education Statistics | Home\nV...
13  Selected Higher Education Statistics | Home\nV...
14  Selected Higher Education Statistics | Home\nV...
15  Selected Higher Education Statistics | Home\nV...
16  Selected Higher Education Statistics | Home\nV...
17  Selected Higher Education Statistics | Home\nV...
18  Selected Higher Education Statistics | Home\nV...
19  Selected Higher Education Statistics | Home\nV...
20  Selected Higher Education Statistics | Home\nV...
21  Verified data for years 2015 to 2024 | Source:...
22  Verified data for years 2015 to 2024 | Source:...
23  Verified data for years 2015 to 2024 | Source:...
24  Verified data for years 2015 to 2024 | Source:...
25  Verified data for years 2015 to 2024 | Source:...
26  Verified data for years 2015 to 2024 | Source:...
27  Verified data for years 2015 to 2024 | Source:...
28  Verified data for years 2015 to 2024 | Source:...
29  Verified data for years 2015 to 2024 | Source:...
30  Verified data for years 2015 to 2024 | Source:...
31  Verified data for years 2015 to 2024 | Source:...
32  Verified data for years 2015 to 2024 | Source:...
33  Verified data for years 2015 to 2024 | Source:...

In [3]:
# Save to CSV
df.to_csv('../data/clean/EnrollmentsAUS_scraped.csv', index=False)

In [5]:
import os
import pandas as pd
from IPython.display import display

attached_data_path = os.path.join('..', 'data', 'raw', 'EnrollmentsAUS_attached.csv')
attached_df = pd.read_csv(attached_data_path)

display(attached_df)

,Category,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Postgraduate (Research),65010,66145,66455,66578,66337,64895,67198,66580,66503
1,Postgraduate (Other),348848,361540,390390,420199,430311,416823,400384,458521,508045
2,Bachelor,970932,971664,992089,1005614,1007034,1016411,981833,966588,984225
3,Sub-Bachelor,66503,65709,65845,67256,71077,68936,68506,73178,78443
4,Enabling,28500,28901,28389,30752,32634,25659,21211,19396,20998
5,Non-award/Microcredentials,15416,19424,19352,19399,15474,9849,12279,16300,17863
6,Total,1495209,1513383,1562520,1609798,1622867,1602573,1551411,1600563,1676077

In [6]:
import os
import pandas as pd
from IPython.display import display

broad_field_data_path = os.path.join('..', 'data', 'raw', 'EnrollmentsAUS_broad_field_attached.csv')
broad_field_df = pd.read_csv(broad_field_data_path)

display(broad_field_df)

,Category,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Natural & Physical Science,119102,124209,129609,134334,136733,139629,134424,132406,134511
1,Information Technology,66355,80090,99986,116623,120916,116296,119278,143253,164464
2,Engineering & Related Tech,111060,115231,119909,121980,118229,112931,109812,115197,122954
3,Architecture & Building,32074,35604,39459,42370,43478,43773,42327,42174,40942
4,Environment & Related,18537,18260,18055,18747,21916,20776,19476,19284,19376
5,Health,235033,247198,256324,265586,277590,288385,280887,283060,295498
6,Education,128277,128603,126360,127202,135250,141971,136096,137387,153177
7,Management & Commerce,380800,389836,396813,399609,380050,352882,340454,360236,368989
8,Society & Culture,312569,322471,326071,332155,343667,350654,334897,326512,329590
9,Creative Arts,93916,94955,96195,97478,97745,98528,93412,92496,96142
10,Others,34729,34930,34128,35058,29164,20676,21363,26127,28530
11,Total,1457209,1513383,1562520,1609798,1622867,1602573,1551411,1600563,1676077